"""Tests for the committed non-code files config points at.

These drift silently: config.toml names a prompt file, .env.example names the
secrets, and nothing fails until a job runs at 6am. Pin them here instead.

``memory/league.md`` is deliberately *not* one of them. It is generated by
``hal-mary sync`` from the live ESPN payload and contains real leaguemates'
names and the league id, so it is gitignored and only the placeholder template
``memory/league.example.md`` is tracked. The template is what ships, so the
template is what these tests pin.
"""

import re
import subprocess
from pathlib import Path

import pytest

from hal_mary.config import ENV_KEYS, load_settings

REPO = Path(__file__).resolve().parents[2]

#: The tracked placeholder. ``league.md`` itself is generated and gitignored.
LEAGUE_TEMPLATE = "league.example.md"


def test_env_example_documents_every_env_key():
    text = (REPO / ".env.example").read_text(encoding="utf-8")
    missing = [key for key in ENV_KEYS if f"{key}=" not in text]
    assert missing == []


def test_env_example_carries_no_real_values():
    """Every assignment is empty or an obvious placeholder — secrets never enter git."""
    for line in (REPO / ".env.example").read_text(encoding="utf-8").splitlines():
        line = line.strip()
        if not line or line.startswith("#") or "=" not in line:
            continue
        key, _, value = line.partition("=")
        assert key in ENV_KEYS, f"unexpected key in .env.example: {key}"
        assert value == "" or value.startswith("<"), f"{key} looks like a real value"


def test_system_prompt_file_exists_and_is_substantial():
    settings = load_settings(env={})
    prompt = settings.claude.system_prompt_file
    assert prompt.is_file()
    assert len(prompt.read_text(encoding="utf-8")) > 500


def test_configured_directories_exist():
    settings = load_settings(env={})
    assert settings.paths.prompts_dir.is_dir()
    assert settings.paths.memory_dir.is_dir()


def test_standing_memory_files_exist():
    settings = load_settings(env={})
    memory = settings.paths.memory_dir
    assert (memory / "caroline.md").is_file()
    assert (memory / LEAGUE_TEMPLATE).is_file()


def test_memory_files_are_marked_human_editable():
    settings = load_settings(env={})
    text = (settings.paths.memory_dir / "caroline.md").read_text(encoding="utf-8")
    assert "human-editable" in text.lower()


#: Task 5's rewrite of memory/league.md must preserve everything below this line
#: verbatim. Pinned here because it is a contract between two tasks, not prose.
LEAGUE_PRESERVE_SENTINEL = "<!-- hal-mary:preserve-below -->"


def test_league_memory_has_a_machine_readable_preserve_sentinel():
    settings = load_settings(env={})
    text = (settings.paths.memory_dir / LEAGUE_TEMPLATE).read_text(encoding="utf-8")
    assert text.count(LEAGUE_PRESERVE_SENTINEL) == 1
    before, _, after = text.partition(LEAGUE_PRESERVE_SENTINEL)
    assert "---" in before, "the sentinel is preceded by a horizontal rule"
    assert after.strip(), "the sentinel is not the last line; hand-written notes go below it"


def test_league_memory_explains_what_the_sentinel_means():
    settings = load_settings(env={})
    text = (settings.paths.memory_dir / LEAGUE_TEMPLATE).read_text(encoding="utf-8")
    assert "hal-mary sync" in text
    assert "preserved" in text.lower()


# --- the generated file must stay out of git -------------------------------


def test_generated_league_memory_is_gitignored():
    """`hal-mary sync` writes real leaguemates' names into memory/league.md.

    One broad `git add` would make them permanent — names in git history cannot
    be removed by a later commit. This asserts the structural guard, so a future
    edit to .gitignore cannot silently re-expose the file.
    """
    result = subprocess.run(
        ["git", "check-ignore", "-v", "memory/league.md"],
        cwd=REPO,
        capture_output=True,
        text=True,
        check=False,
    )
    assert result.returncode == 0, "memory/league.md is not gitignored"
    assert ".gitignore" in result.stdout


def test_generated_league_memory_is_not_tracked():
    tracked = subprocess.run(
        ["git", "ls-files", "memory/"],
        cwd=REPO,
        capture_output=True,
        text=True,
        check=True,
    ).stdout.split()
    assert "memory/league.md" not in tracked
    assert f"memory/{LEAGUE_TEMPLATE}" in tracked


#: A league id is a long run of digits; a leaguemate is two capitalised words.
#: Deliberately crude — its job is to fail loudly if someone pastes the output
#: of a real sync over the template, not to be a classifier.
_LOOKS_LIKE_AN_ID = re.compile(r"\d{3,}")
_LOOKS_LIKE_A_FULL_NAME = re.compile(r"\b[A-Z][a-z]+ [A-Z][a-z]+\b")


def test_league_template_carries_no_real_league_data():
    settings = load_settings(env={})
    text = (settings.paths.memory_dir / LEAGUE_TEMPLATE).read_text(encoding="utf-8")

    assert not _LOOKS_LIKE_AN_ID.search(text), "the template looks like it contains a league id"
    assert not _LOOKS_LIKE_A_FULL_NAME.search(text), (
        "the template looks like it contains a person's name"
    )


def test_no_build_artifact_is_tracked():
    """A virtualenv, a browser dump or a screenshot must never be committed.

    This is not hypothetical tidiness. A `.venv -> <repo>/.venv` symlink, made
    so several git worktrees could share one interpreter, was swept up by
    `git add -A` and committed: `.gitignore` said `.venv/`, and a trailing
    slash ignores a *directory* of that name, not a *symlink*. Checking that
    branch out then replaced the real virtualenv with a link to itself, and
    every `uv run` died with "Too many levels of symbolic links" — a failure
    that looks nothing like its cause.
    """
    tracked = subprocess.run(
        ["git", "ls-files"], cwd=REPO, capture_output=True, text=True, check=True
    ).stdout.split()

    forbidden = [
        name
        for name in tracked
        if name == ".venv"
        or name.startswith((".venv/", ".playwright-mcp/", "node_modules/"))
        # Screenshots under docs/ are deliberate: the README shows the app, and
        # a picture of it is the one thing prose cannot do. They are generated
        # by `scripts/demo_seed.py` + a headless browser against DEMO data, so
        # no real league member appears in one. A .png anywhere else is still a
        # stray artifact.
        or (name.endswith(".png") and not name.startswith("docs/screenshots/"))
        or name.endswith(".pyc")
        # A database, or any copy of one. The live database holds real
        # leaguemates' names, so a backup committed to the repo is the same
        # disclosure wearing a timestamp. One reached `main` on 2026-09-08.
        or ".db" in name
    ]
    assert not forbidden, f"build artifacts are tracked: {forbidden}"


def test_no_tracked_file_is_a_symlink():
    """Nothing in this repo needs to be a symlink, and one already cost a day.

    `git ls-files -s` reports mode 120000 for a symlink. Pinning the mode
    catches the next one whatever it is called, rather than only the `.venv`
    that happened to bite first.
    """
    listing = subprocess.run(
        ["git", "ls-files", "-s"], cwd=REPO, capture_output=True, text=True, check=True
    ).stdout.splitlines()

    links = [line.split("\t", 1)[1] for line in listing if line.startswith("120000")]
    assert not links, f"tracked symlinks: {links}"


def test_no_tracked_file_carries_the_real_league_id():
    """The league id is an identifier for a private league, like a SWID.

    This one nearly went in. The commit that taught the fixture recorder to
    substitute the league id used the *real* id as the example payload in its
    own test — the leak, written into the test that exists to prevent it. A
    number is not obviously a secret the way `ESPN_S2=AEB...` is, so nothing
    reading the diff flinched.

    This is a question about the **box**, not about this code: it can only be
    asked where the real id is configured. On a box without one it skips and
    says so, and on Bryan's box and the production VM it runs and bites. Names
    and ids in git history cannot be removed by a later commit, so the check
    has to happen before the commit, not after.
    """
    league_id = load_settings().league_id
    if not league_id:
        pytest.skip("no LEAGUE_ID configured on this box; nothing to search for")

    result = subprocess.run(
        ["git", "grep", "-I", "-l", "-F", str(league_id)],
        cwd=REPO,
        capture_output=True,
        text=True,
        check=False,
    )
    # `git grep` exits 1 for "no matches", which is the answer we want, and 2+
    # for "I could not look" — which must not read as a clean bill of health.
    assert result.returncode in (0, 1), f"git grep failed: {result.stderr.strip()}"

    tracked = result.stdout.split()
    assert not tracked, f"the real league id appears in tracked files: {tracked}"
