"""Tests for the committed non-code files config points at.

These drift silently: config.toml names a prompt file, .env.example names the
secrets, and nothing fails until a job runs at 6am. Pin them here instead.

``memory/league.md`` is deliberately *not* one of them. It is generated by
``hal-mary sync`` from the live ESPN payload and contains real leaguemates'
names and the league id, so it is gitignored and only the placeholder template
``memory/league.example.md`` is tracked. The template is what ships, so the
template is what these tests pin.
"""

import re
import subprocess
from pathlib import Path

from hal_mary.config import ENV_KEYS, load_settings

REPO = Path(__file__).resolve().parents[2]

#: The tracked placeholder. ``league.md`` itself is generated and gitignored.
LEAGUE_TEMPLATE = "league.example.md"


def test_env_example_documents_every_env_key():
    text = (REPO / ".env.example").read_text(encoding="utf-8")
    missing = [key for key in ENV_KEYS if f"{key}=" not in text]
    assert missing == []


def test_env_example_carries_no_real_values():
    """Every assignment is empty or an obvious placeholder — secrets never enter git."""
    for line in (REPO / ".env.example").read_text(encoding="utf-8").splitlines():
        line = line.strip()
        if not line or line.startswith("#") or "=" not in line:
            continue
        key, _, value = line.partition("=")
        assert key in ENV_KEYS, f"unexpected key in .env.example: {key}"
        assert value == "" or value.startswith("<"), f"{key} looks like a real value"


def test_system_prompt_file_exists_and_is_substantial():
    settings = load_settings(env={})
    prompt = settings.claude.system_prompt_file
    assert prompt.is_file()
    assert len(prompt.read_text(encoding="utf-8")) > 500


def test_configured_directories_exist():
    settings = load_settings(env={})
    assert settings.paths.prompts_dir.is_dir()
    assert settings.paths.memory_dir.is_dir()


def test_standing_memory_files_exist():
    settings = load_settings(env={})
    memory = settings.paths.memory_dir
    assert (memory / "caroline.md").is_file()
    assert (memory / LEAGUE_TEMPLATE).is_file()


def test_memory_files_are_marked_human_editable():
    settings = load_settings(env={})
    text = (settings.paths.memory_dir / "caroline.md").read_text(encoding="utf-8")
    assert "human-editable" in text.lower()


#: Task 5's rewrite of memory/league.md must preserve everything below this line
#: verbatim. Pinned here because it is a contract between two tasks, not prose.
LEAGUE_PRESERVE_SENTINEL = "<!-- hal-mary:preserve-below -->"


def test_league_memory_has_a_machine_readable_preserve_sentinel():
    settings = load_settings(env={})
    text = (settings.paths.memory_dir / LEAGUE_TEMPLATE).read_text(encoding="utf-8")
    assert text.count(LEAGUE_PRESERVE_SENTINEL) == 1
    before, _, after = text.partition(LEAGUE_PRESERVE_SENTINEL)
    assert "---" in before, "the sentinel is preceded by a horizontal rule"
    assert after.strip(), "the sentinel is not the last line; hand-written notes go below it"


def test_league_memory_explains_what_the_sentinel_means():
    settings = load_settings(env={})
    text = (settings.paths.memory_dir / LEAGUE_TEMPLATE).read_text(encoding="utf-8")
    assert "hal-mary sync" in text
    assert "preserved" in text.lower()


# --- the generated file must stay out of git -------------------------------


def test_generated_league_memory_is_gitignored():
    """`hal-mary sync` writes real leaguemates' names into memory/league.md.

    One broad `git add` would make them permanent — names in git history cannot
    be removed by a later commit. This asserts the structural guard, so a future
    edit to .gitignore cannot silently re-expose the file.
    """
    result = subprocess.run(
        ["git", "check-ignore", "-v", "memory/league.md"],
        cwd=REPO,
        capture_output=True,
        text=True,
        check=False,
    )
    assert result.returncode == 0, "memory/league.md is not gitignored"
    assert ".gitignore" in result.stdout


def test_generated_league_memory_is_not_tracked():
    tracked = subprocess.run(
        ["git", "ls-files", "memory/"],
        cwd=REPO,
        capture_output=True,
        text=True,
        check=True,
    ).stdout.split()
    assert "memory/league.md" not in tracked
    assert f"memory/{LEAGUE_TEMPLATE}" in tracked


#: A league id is a long run of digits; a leaguemate is two capitalised words.
#: Deliberately crude — its job is to fail loudly if someone pastes the output
#: of a real sync over the template, not to be a classifier.
_LOOKS_LIKE_AN_ID = re.compile(r"\d{3,}")
_LOOKS_LIKE_A_FULL_NAME = re.compile(r"\b[A-Z][a-z]+ [A-Z][a-z]+\b")


def test_league_template_carries_no_real_league_data():
    settings = load_settings(env={})
    text = (settings.paths.memory_dir / LEAGUE_TEMPLATE).read_text(encoding="utf-8")

    assert not _LOOKS_LIKE_AN_ID.search(text), "the template looks like it contains a league id"
    assert not _LOOKS_LIKE_A_FULL_NAME.search(text), (
        "the template looks like it contains a person's name"
    )
